INSERT INTO students (
    id, programme, start_year, end_year, name, department, supervisor, 
    permanent_email, niser_email, professional_email, other_emails, 
    phone_number, career_path, research_interests, current_position, 
    current_institute, future_plans, social_media_links, 
    comments_for_batch, additional_info, photo_url
) VALUES 
(
    'usr_4jkl', 
    'PhD', 
    2017, 
    2022, 
    'Dr. Ananya Sharma', 
    'SBS', 
    'Dr. S. K. Patel', 
    'ananya.s@gmail.com', 
    'ananya.sharma@niser.ac.in', 
    'asharma@ncbs.res.in', 
    'ananya_work@yahoo.com', 
    '+91-9876543210', 
    'Completed PhD in neurobiology, then moved to NCBS for a postdoc fellowship focusing on memory consolidation.', 
    'Neuroscience, Memory Consolidation, Optogenetics', 
    'Postdoctoral Fellow', 
    'National Centre for Biological Sciences (NCBS)', 
    'Aiming for a faculty position in India within the next 2 years.', 
    'https://linkedin.com/in/ananyasharma,https://twitter.com/ananya_neuro', 
    'Miss the late-night canteen sessions! Hope everyone is doing great.', 
    'Currently open to collaboration on behavioral assay projects.', 
    'https://i.pravatar.cc/150?img=47'
),
(
    'usr_5mno', 
    'Int. MSc.', 
    2015, 
    2020, 
    'Vikram Singh', 
    'SPS', 
    'Dr. R. K. Das', 
    'vikram.physics@outlook.com', 
    'vikram.singh@niser.ac.in', 
    'vsingh@cern.ch', 
    '', 
    '+41-791234567', 
    'Joined CERN as a data analyst after my Master thesis. Now pursuing my PhD concurrently.', 
    'High Energy Physics, Particle Detectors, Machine Learning', 
    'Doctoral Researcher', 
    'CERN / University of Geneva', 
    'Transitioning into data science roles in the European tech industry.', 
    'https://linkedin.com/in/vikramsingh-hep,https://github.com/vikram-phys', 
    'SPS folks, let me know if anyone is visiting Geneva!', 
    'Happy to mentor juniors interested in experimental high-energy physics.', 
    'https://i.pravatar.cc/150?img=11'
),
(
    'usr_6pqr', 
    'Faculty', 
    2012, 
    2050, 
    'Dr. Meera Iyer', 
    'SMS', 
    'N/A', 
    'meera.iyer.math@gmail.com', 
    'meera.iyer@niser.ac.in', 
    'meera.iyer@niser.ac.in', 
    '', 
    '+91-6742490000', 
    'Did postdoc at TIFR before joining NISER as Assistant Professor.', 
    'Algebraic Geometry, Commutative Algebra', 
    'Assistant Professor', 
    'NISER Bhubaneswar', 
    'Organizing an international conference on Algebraic Geometry next year.', 
    'https://math.niser.ac.in/~meera', 
    'Always proud to see our math alumni thriving across the globe.', 
    'Looking for motivated PhD students to join my research group.', 
    'https://i.pravatar.cc/150?img=32'
);